export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
export { default as Hero } from "./Hero";
export { default as Treatments } from "./Treatments";
export { default as Carousel } from "./Carousel";
export { default as Testimonials } from "./Testimonials";
export { default as Gallery } from "./Gallery";
export { default as Input } from "./Input";
export { default as Enquiry } from "./Enquiry";
